### PR TITLE
changed find.py to ttk

### PR DESCRIPTION
**Pull request by Zaab1t**
as you requested in #15. I don't think it's acting as intended though. I might look into it this weekend :)

### CODE REVIEW

**Comment by Akuli** [comment]
`__Myst__` has written a couple versions of the `find.py`, and they have been "working" but I haven't been very happy with them. Currently it has at least these issues:

- Pressing any key while the main area is focused moves the focus to the find area.
- Try find/replacing something in a long file and skipping some matches. After every replace, clicking the find button finds the first match in the whole file instead of next after the replace.
- Copy/pasting is very broken, but that's my fault. It's broken in all other entries as well because it's a global binding (and it shouldn't be).

Don't feel bad if you rewrite the whole thing. After all I'm really happy to have someone fixing the find area for me. It has been annoying for several months now, and I have used Porcupine as my main editor most of that time.

**Comment by Akuli** [comment]
Are you still interested in working on this? The copy/pasting issue is fixed in new porcupines.

**Comment by Akuli** [comment]
Alright, over a year of find area bugginess :D I remember using porcupine with the buggy find area at work last summer.

**Comment by Zaab1t** [comment]
Can I close this issue? find needs a complete rework imo

**Comment by Akuli** [comment]
yes

**Comment by Akuli** [comment]
the complete rework is done now, i rewrote the whole thing

**Pull request closed without merging**
