### PR TITLE
Menubar State Not Resetting Between Tests

### PR DESCRIPTION
**Pull request by benjamin-kirkbride**
Fixes https://github.com/Akuli/porcupine/issues/1401

### CODE REVIEW

**Comment by benjamin-kirkbride** [comment]
Possibly related to https://github.com/Akuli/porcupine/issues/1329

**Comment by Akuli** [comment]
My first instinct was to say that your tests shouldn't add things to menubar. Usually you add to menubar in plugins and then check the state of the menubar in tests.

But looking at what your test does, I see why you want this. Some ideas:
- Create a fixture that adds a whole new menu for a test, say `get_menu("Testing Temp Menu")`, and then deletes that entire menu once the test completes?
- Test `menubar._split_parent()` and similar functions in their various corner cases, and trust that the rest of the menubar plugin calls them correctly? This gives us confidence that if it works in "normal" cases, it also works in weird corner cases.

**Comment by benjamin-kirkbride** [comment]
I guess I assumed this was unexpected and undesirable behavior.

In previous discussions, particularly revolving around #1329, was that we were not expecting any state to be persisted between tests.

IMO, things like this need to be eliminated wherever they are found if we want to be able to consistently support parallelization of tests (which I do desperately want).

**Comment by Akuli** [comment]
With the way the tests work right now, Porcupine is started once, and then all tests run consecutively in the Porcupine instance. This means that there will always be various ways to influence one test from another if you try.

"Restarting" Porcupine between the tests isn't really an option, if it means that `setup()` functions in all plugins would be called again. I imagine that would make testing a lot slower. It's not very easy to try it now, because there's currently no good way to restart Porcupine without launching a whole new Python process.

**Comment by benjamin-kirkbride** [comment]
Alright, seems like there isn't anything to be done here other than maybe make a fixture and possibly document this as a footgun in the dev docs

**Comment by benjamin-kirkbride** [comment]
What exactly are we envisioning here for documentation? A docstring at the top of the menubar test file? A section in CONTRIBUTING.md?

**Comment by Akuli** [comment]
I'm thinking a new markdown file all about docs. It would explain, among other things:
- what resets between tests and why
- what doesn't reset between tests and using fixtures to work around this

**Comment by Akuli** [comment]
There is now a markdown file about tests that explains why menus behave like they do.

IMO this problem isn't worth fixing, because relatively only a few tests add stuff to menus, and in general, tests shouldn't be confused if there is extra stuff in the menus.

**Pull request closed without merging**
