### PR TITLE
Change master to main in a few places

### PR DESCRIPTION
**Pull request by Akuli**

### CODE REVIEW

**Comment by Moosems** [comment]
Why?

**Comment by Akuli** [comment]
I renamed the branch a while ago (#1213). GitHub still redirects from "master" URLs to "main" URLS (e.g. https://github.com/Akuli/porcupine/blob/master/LICENSE redirects to https://github.com/Akuli/porcupine/blob/main/LICENSE ), but I think it's nice to be consistent about it.

**Comment by Moosems** [comment]
Why'd you change it in the first place?

**Comment by Akuli** [comment]
To me, the main reason is that "the main branch" now makes more sense to most contributors than "the master branch", because many other projects have changed to `main` and it's the default in github. There are other reasons too, search for e.g. "why main instead of master branch".

**Pull request merged**
