### PR TITLE
Upgrade typing syntax

### PR DESCRIPTION
**Pull request by rdbende**
Used [`pyupgrade`](https://github.com/asottile/pyupgrade) to upgrade typing syntax. Might still have unused imports?

### CODE REVIEW

**Comment by Moosems** [comment]
Using `ruff .` will quickly tell you if there’re any unused imports 😄.

**Comment by rdbende** [comment]
The CI did that for me.

**Comment by Akuli** [comment]
Is it possible to make the CI do this automatically for us? Ideally with ruff, but pyupgrade in CI is also fine if ruff can't do all the things as pyupgrade does. Of course, if there's no way to say "please keep the old syntax on this line", that is a no :)

**Comment by rdbende** [comment]
`--keep-runtime-typing` seems to fix the issue with dataclasses. Will add it to the autofix

**Comment by Akuli** [comment]
Replaced by #1387 and #1388.

**Pull request closed without merging**
