### PR TITLE
Pastebins

### PR DESCRIPTION
**Pull request by adder46**
Replaced dpaste.de with dpaste.org, removed ghostbin which wasn't working.

### CODE REVIEW

**Comment by PurpleMyst** [comment]
I think you got the wrong branch and you actually want to merge into `langserver`, not `master`

**Comment by Akuli** [comment]
I did some weird git magic in bdc598a0c19fb

**Comment by PurpleMyst** [comment]
cherry-pick ftw

**Comment by Akuli** [comment]
I rebased this one, could have also cherry-picked

**Pull request closed without merging**
