### PR TITLE
Add pyupgrade to autofix GHA

### PR DESCRIPTION
**Pull request by rdbende**

### CODE REVIEW

**Comment by Akuli** [comment]
Github actions runs the workflow from main for security reasons (it has enough permissions to push to any branch). Feel free to push to main for experimenting with this PR.

**Comment by rdbende** [comment]
Ok, I'm starting to understand, what I'm supposed to do, lol

**Comment by rdbende** [comment]
> Ok, I'm starting to understand, what I'm supposed to do, lol

Or not 😅. Shouldn't we merge this PR?

**Comment by Akuli** [comment]
Let's merge and see what happens, as there's no good way to test without merging :)

**Pull request merged**
