### PR TITLE
About dialog link color dark

### LINKED ISSUE #503: Text in About dialog hard on the eyes in dark mode
Difficult to read the about dialog's blue text on black background (Mac)

Screenshot 2021-06-12 at 11 25 01

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #503. Needs @ThePhilgrim  review.

about

### CODE REVIEW

**Comment by Akuli** [comment]
I messed up something with git, lol

**Comment by ThePhilgrim** [comment]
Hmm, how do I checkout a non-local branch from the main repo when I'm on a forked repo?

**Comment by Akuli** [comment]
Good question. Here's how I would do it. It's not in git-guide yet:

```
$ git remote add akuli https://github.com/Akuli/porcupine
$ git fetch akuli
$ git checkout akuli/linkcolor
```

The first command adds a remote named `akuli` (you can name it however you want). By default, there's only one remote: `origin`, aka where you cloned from, aka https://github.com/ThePhilgrim/porcupine. Now there's two, `origin` (you) and `akuli` (me).

Once you have added the new `akuli` remote, nothing is downloaded by default, and you need to do it explicitly (git fetch). Also, pulling from my master becomes a bit easier too: you can use `git pull akuli master` instead of `git pull https://github.com/Akuli/porcupine`.

**Review by ThePhilgrim — APPROVED** [review]
Looks very nice!

Screenshot 2021-06-12 at 12 17 25

**Pull request merged**
