### PR TITLE
highlight only visible part of file (using ugly generator hack)

### LINKED ISSUE #39: highlight plugin rehighlights entire file every time a single character changes
To fix this, I can't just start highlighting from the part of the file visible at the very top of the editor window, because a multi-line Python `"""` string or a C `/*` comment could begin before the top of the view and end after the top of the view. In cases like this, it's necessary to look at what's before the view.

Ideally I would have an object that tokenizes code, let's call it a token iterator, with these features:
- I can feed code to the token iterator in little chunks if I want.
- I can create a copy of the token iterator.

With just these features, I could create a token iterator and feed it everything before the top of the view **once**, and use copies of that iterator for highlighting what's currently being shown. Then editing somewhere inside the view would mean creating a new copy of the token iterator and rehighlighting the visible part of the code with that.

Python's generators have `.send()` which could be used for feeding code in chunks, but they are not copyable:

```
>>> def stupid_tokenizer(string):
...     for word in string.split():
...         yield word
... 
>>> iterator = stupid_tokenizer('bla bla lol bla lol wutz hehe')
>>> next(iterator)
'bla'
>>> import copy
>>> copy.copy(iterator)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/copy.py", line 96, in copy
    rv = reductor(4)
TypeError: can't pickle generator objects
>>> 
```

Currently Pygments provides a Python generator and not much else.

### PR DESCRIPTION
**Pull request by Akuli**
fixes #39

### CODE REVIEW

**Comment by Akuli** [comment]
Note to self: this can be optimized even more for key presses by not rehighlighting the entire view

**Review by PurpleMyst — APPROVED** [review]
Man this is cursed. But, it looks good to me. Only nitpick I might have is that it might be a good idea to put the exact version of pygments you know this works for in `requirements.txt`

**Comment by Akuli** [comment]
>approved these changes

>Man this is cursed.

I would have never thought that these could appear in the same review... :heart:

**Comment by Akuli** [comment]
Non-RegexLexers such as MakefileLexer are a bit of a problem. I tried editing a Makefile with 120 lines in it, and the slowness was already noticable. There are lots of lexers like this:

<details>

```
from pygments.lexer import RegexLexer
from pygments.lexers import get_lexer_by_name, get_all_lexers

all_lexers = [get_lexer_by_name(a[1][0]) for a in get_all_lexers() if a[1]]
for lee in all_lexers:
    if not isinstance(lee, RegexLexer):
        print(lee)

# Output:
#    <pygments.lexers.Angular2HtmlLexer>
#    <pygments.lexers.AntlrActionScriptLexer>
#    <pygments.lexers.AntlrCSharpLexer>
#    <pygments.lexers.AntlrCppLexer>
#    <pygments.lexers.AntlrJavaLexer>
#    <pygments.lexers.AntlrObjectiveCLexer>
#    <pygments.lexers.AntlrPerlLexer>
#    <pygments.lexers.AntlrPythonLexer>
#    <pygments.lexers.AntlrRubyLexer>
#    <pygments.lexers.BashSessionLexer>
#    <pygments.lexers.CObjdumpLexer>
#    <pygments.lexers.CSharpAspxLexer>
#    <pygments.lexers.CheetahHtmlLexer>
#    <pygments.lexers.CheetahJavascriptLexer>
#    <pygments.lexers.CheetahXmlLexer>
#    <pygments.lexers.ColdfusionCFCLexer>
#    <pygments.lexers.ColdfusionHtmlLexer>
#    <pygments.lexers.CppObjdumpLexer>
#    <pygments.lexers.CssDjangoLexer>
#    <pygments.lexers.CssErbLexer>
#    <pygments.lexers.CssGenshiLexer>
#    <pygments.lexers.CssPhpLexer>
#    <pygments.lexers.CssSmartyLexer>
#    <pygments.lexers.DObjdumpLexer>
#    <pygments.lexers.DelphiLexer>
#    <pygments.lexers.DylanConsoleLexer>
#    <pygments.lexers.ElixirConsoleLexer>
#    <pygments.lexers.EmailLexer>
#    <pygments.lexers.ErbLexer>
#    <pygments.lexers.ErlangShellLexer>
#    <pygments.lexers.EvoqueHtmlLexer>
#    <pygments.lexers.EvoqueXmlLexer>
#    <pygments.lexers.GenshiLexer>
#    <pygments.lexers.GosuTemplateLexer>
#    <pygments.lexers.HandlebarsHtmlLexer>
#    <pygments.lexers.HtmlDjangoLexer>
#    <pygments.lexers.HtmlGenshiLexer>
#    <pygments.lexers.HtmlPhpLexer>
#    <pygments.lexers.HtmlSmartyLexer>
#    <pygments.lexers.JavascriptDjangoLexer>
#    <pygments.lexers.JavascriptErbLexer>
#    <pygments.lexers.JavascriptGenshiLexer>
#    <pygments.lexers.JavascriptPhpLexer>
#    <pygments.lexers.JavascriptSmartyLexer>
#    <pygments.lexers.JsonLdLexer>
#    <pygments.lexers.JsonLexer>
#    <pygments.lexers.JspLexer>
#    <pygments.lexers.JuliaConsoleLexer>
#    <pygments.lexers.LassoCssLexer with {'requiredelimiters': True}>
#    <pygments.lexers.LassoHtmlLexer>
#    <pygments.lexers.LassoJavascriptLexer with {'requiredelimiters': True}>
#    <pygments.lexers.LassoXmlLexer>
#    <pygments.lexers.LiterateAgdaLexer with {'litstyle': 'latex'}>
#    <pygments.lexers.LiterateCryptolLexer>
#    <pygments.lexers.LiterateHaskellLexer>
#    <pygments.lexers.LiterateIdrisLexer>
#    <pygments.lexers.MSDOSSessionLexer>
#    <pygments.lexers.MakefileLexer>
#    <pygments.lexers.MakoCssLexer>
#    <pygments.lexers.MakoHtmlLexer>
#    <pygments.lexers.MakoJavascriptLexer>
#    <pygments.lexers.MakoXmlLexer>
#    <pygments.lexers.MatlabSessionLexer>
#    <pygments.lexers.MozPreprocCssLexer>
#    <pygments.lexers.MozPreprocJavascriptLexer>
#    <pygments.lexers.MozPreprocXulLexer>
#    <pygments.lexers.MyghtyCssLexer>
#    <pygments.lexers.MyghtyHtmlLexer>
#    <pygments.lexers.MyghtyJavascriptLexer>
#    <pygments.lexers.MyghtyXmlLexer>
#    <pygments.lexers.PostgresConsoleLexer>
#    <pygments.lexers.PowerShellSessionLexer>
#    <pygments.lexers.PsyshConsoleLexer with {'startinline': True}>
#    <pygments.lexers.PythonConsoleLexer>
#    <pygments.lexers.RConsoleLexer>
#    <pygments.lexers.RagelCLexer>
#    <pygments.lexers.RagelCppLexer>
#    <pygments.lexers.RagelDLexer>
#    <pygments.lexers.RagelJavaLexer>
#    <pygments.lexers.RagelObjectiveCLexer>
#    <pygments.lexers.RagelRubyLexer>
#    <pygments.lexers.RawTokenLexer>
#    <pygments.lexers.RhtmlLexer>
#    <pygments.lexers.RobotFrameworkLexer with {'tabsize': 2, 'encoding': 'UTF-8'}>
#    <pygments.lexers.RubyConsoleLexer>
#    <pygments.lexers.SlashLexer>
#    <pygments.lexers.SqliteConsoleLexer>
#    <pygments.lexers.SspLexer>
#    <pygments.lexers.TNTLexer>
#    <pygments.lexers.TcshSessionLexer>
#    <pygments.lexers.TeaTemplateLexer>
#    <pygments.lexers.TextLexer>
#    <pygments.lexers.TreetopLexer>
#    <pygments.lexers.TwigHtmlLexer>
#    <pygments.lexers.VbNetAspxLexer>
#    <pygments.lexers.VelocityHtmlLexer>
#    <pygments.lexers.VelocityXmlLexer>
#    <pygments.lexers.XmlDjangoLexer>
#    <pygments.lexers.XmlErbLexer>
#    <pygments.lexers.XmlPhpLexer>
#    <pygments.lexers.XmlSmartyLexer>
#    <pygments.lexers.YamlJinjaLexer>
```

</details>

I'm arfaid I'll also need to support the older kind of subprocess highlighting.

**Comment by Akuli** [comment]
Also, it's still too slow for huge `.pyi` stub files, even though the log messages say that it only takes about 10ms to highlight on key press. But something else has to be slow then, because with TextLexer it's not at all laggy.

**Comment by Akuli** [comment]
Non-RegexLexer perf issue fixed, huge pyi issue turned out to be not highlight plugin's fault (see #222 )

**Pull request merged**
