### PR TITLE
 right-click menu placing

### LINKED ISSUE #1429: right-click menu placing
2023-12-06-134224_1920x1080_scrot

The right-click menu appears exactly where the mouse is. This makes it easy to accidentally click the first menu item. It would be better to place the menu e.g. 10px below the mouse.

Porcupine has several right-click menus, and they should be all fixed at once. They all use the `tk_popup()` menu, so to find all places that need to be changed, you can search for `tk_popup` in the project (with e.g. `git grep tk_popup`).

### PR DESCRIPTION
**Pull request by ethical-haquer**
Added 10 pixels offset to right-click menus
Fixes #1429

### CODE REVIEW

**Review by Akuli — COMMENTED** [review]
Thanks! A couple things:
- You missed one of the four menus. Run `git grep tk_popup` to find all places where menus are shown.
- These also need y offset.

**Comment by Akuli** [comment]
The y offset is needed in situations where the menu shows near the right edge of the screen. For example, when right-clicking the text widget, this can happen and the menu should be placed below the cursor:

2024-03-10-193051_1680x1050_scrot

**Comment by ethical-haquer** [comment]
> Thanks! A couple things:
> 
>     * You missed one of the four menus. Run `git grep tk_popup` to find all places where menus are shown.
> 
>     * These also need y offset.

Will do!

**Comment by Akuli** [comment]
IMO 10 pixels is better than 1 pixel. You got that part right initially. Sorry if I wasn't clear :)

**Review by Akuli — APPROVED** [review]
Thanks! I tried it on my computer and the new behavior is awesome :)

**Comment by ethical-haquer** [comment]
> Thanks! I tried it on my computer and the new behavior is awesome :)

Your welcome! I figured I had better start on something small. 🤣
Thanks for guiding me through the process and answering my numerous questions!

**Pull request merged**
